# Generated by Django 2.0 on 2019-01-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
