# Generated by Django 2.0 on 2018-12-04 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deck', '0002_deck_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.NullBooleanField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_exchanges', to=settings.AUTH_USER_MODEL)),
                ('applicant_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_card_exchanges', to='cards.Card')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validator_exchanges', to=settings.AUTH_USER_MODEL)),
                ('validator_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validator_card_exchanges', to='cards.Card')),
            ],
        ),
    ]
