# Generated by Django 2.0 on 2018-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gold',
            field=models.IntegerField(default=500),
        ),
    ]
