# Generated by Django 2.0 on 2018-12-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
        ('user', '0002_auto_20181204_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='clan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clan.Clan'),
        ),
    ]
