# Generated by Django 2.0 on 2019-01-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gold',
            field=models.IntegerField(default=800),
        ),
    ]
