# Generated by Django 2.0 on 2019-01-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tag',
            field=models.IntegerField(default=0),
        ),
    ]
