# Generated by Django 2.0 on 2019-01-09 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0003_card_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points_player1', models.IntegerField(default=0)),
                ('points_player2', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=0)),
                ('nb_plays', models.IntegerField(default=0)),
                ('statut', models.IntegerField(default=0)),
                ('accept', models.IntegerField(null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_match', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_match', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winner_turns', models.IntegerField(default=0)),
                ('statut', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_turns', to='match.Match')),
                ('play_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card1_turns', to='cards.Card')),
                ('play_player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card2_turns', to='cards.Card')),
            ],
        ),
    ]
