# Generated by Django 2.0 on 2019-01-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turns',
            name='play_player1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card1_turns', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='turns',
            name='play_player2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='card2_turns', to='cards.Card'),
        ),
    ]
